name: vosk_flutter_example
description: Demonstrates how to use the vosk_flutter plugin.

publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0"

# 强制使用指定版本插件覆盖
dependency_overrides:
  http: ^1.1.0
  dio: ^4.0.4

dependencies:
  flutter:
    sdk: flutter

  vosk_flutter:
    # When depending on this package from a real application you should use:
    #   vosk_flutter: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  wav: ^1.2.0
  record: ^4.4.4
  #vosk_flutter: ^1.0.5
  #vosk_flutter: ^0.3.48
  #background_downloader: ^7.12.2
  path_provider: ^2.0.9
  flowder_ex: ^0.2.2
  archive: ^3.1.8
  # 进度条
  #percent_indicator: ^4.2.3
  #open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/models/
